### ISSUE TITLE
Handle non-json responses graciously

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-python#51] opened 2018-01-15 14:59 UTC
Currently if a site 500s and sends back non json the SDK will throw `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` instead of parsing the HTML returned as the error string.

**Comment by ConnorMac** [comment] 2018-12-10 03:17
`UnboundLocalError: local variable 'error_data' referenced before assignment` is thrown as well if the JSONDecode error fails.

**Comment by OdinsPlasmaRifle** [comment] 2021-12-09 19:02
Duplicate of #72

**Closed as completed by OdinsPlasmaRifle** 2021-12-09 19:02 UTC
Labels: duplicate
